import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
      <ClerkProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> 
          <Toaster
            theme="system"
            position="bottom-right"
            richColors
            expand={false}
            visibleToasts={3}
            closeButton
            duration={4000}
            toastOptions={{
              classNames: {
                toast: "!w-[calc(100vw-2rem)] !max-w-[calc(100vw-2rem)] sm:!w-[360px] sm:!max-w-[360px] !font-mono !rounded-none !shadow-lg",
                title: "!text-sm !font-semibold",
                description: "!text-xs !break-words",
              },
            }}
          />
        {children}
        </ThemeProvider>
        </ClerkProvider></body>
    </html>
  );
}
